# Python 3 para Análise de Dados
### Básico sobre NumPy
    by Adriano Pylro
    Referências:
        1) Pyhton para Análise de Dados (Wes McKinney)

In [3]:
import numpy as np

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
# gera dados aleatórios
data = np.random.randn(2, 3)
data

array([[ 1.00013736, -0.17980352,  1.46531028],
       [ 0.12655323, -0.5547596 , -0.96749037]])

In [6]:
data * 100

array([[100.01373582, -17.98035203, 146.53102789],
       [ 12.65532317, -55.4759597 , -96.74903675]])

In [7]:
data + data

array([[ 2.00027472, -0.35960704,  2.93062056],
       [ 0.25310646, -1.10951919, -1.93498073]])

In [8]:
# um ndarray é um contêiner genérico multidimensional para dados homogêneos

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [11]:
data1 = [6, 7 , 8, 9, 10]
data1

[6, 7, 8, 9, 10]

In [12]:
arr1 = np.array(data1)
arr1

array([ 6,  7,  8,  9, 10])

In [13]:
data2 = [[1, 2, 3], [4, 5, 6]]
data2

[[1, 2, 3], [4, 5, 6]]

In [14]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.shape

(2, 3)

In [16]:
arr2.ndim

2

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2)) 

array([[[1.20188055e-075, 2.17570432e-076],
        [2.21403296e+160, 9.59373447e-071],
        [5.01163114e+217, 5.49419094e-143]],

       [[9.80058441e+252, 1.30304358e-142],
        [2.14027814e+161, 1.08712259e+243],
        [1.51894018e+243, 1.35617292e+248]]])

In [20]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr[5]

5

In [22]:
arr[5:8]

array([5, 6, 7])

In [23]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [25]:
arr_slice[2] = 69
arr

array([ 0,  1,  2,  3,  4, 12, 12, 69,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr_slice[:] = 2019
arr

array([   0,    1,    2,    3,    4, 2019, 2019, 2019,    8,    9,   10,
         11,   12,   13,   14])

In [28]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr2d[2]

array([7, 8, 9])

In [30]:
arr2d[0][2]

3

In [32]:
arr3d=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# Indexando com fFatias

In [35]:
arr

array([   0,    1,    2,    3,    4, 2019, 2019, 2019,    8,    9,   10,
         11,   12,   13,   14])

In [36]:
arr[1:6]

array([   1,    2,    3,    4, 2019])

In [37]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [41]:
# Métodos Matemáticos e Estatísticos

In [72]:
arr = np.random.randn(5)
arr

array([ 2.24487054,  1.36573982,  0.30783117,  1.45392678, -0.52869766])

In [73]:
arr.mean()

0.9687341294242394

In [74]:
np.mean(arr)

0.9687341294242394

In [75]:
arr.sum()

4.843670647121197

In [76]:
np.sum(arr)

4.843670647121197

In [77]:
arr2 = np.random.randn(5, 4)
arr2

array([[ 0.47723616,  0.29039915, -0.33704234,  0.46842676],
       [-0.32008915,  0.79712032,  0.41222303, -0.36018307],
       [-1.2432528 ,  0.26227853, -0.93510021,  0.63792128],
       [ 0.97162949,  0.89117611,  0.02920054, -1.58786767],
       [-1.86962057,  0.66100158,  0.13200255,  0.53807517]])

In [78]:
arr2.mean()

-0.00422325712807588

In [79]:
arr2.mean(axis = 1) #cálculo da média das linhas

array([ 0.22475493,  0.13226778, -0.3195383 ,  0.07603462, -0.13463532])

In [81]:
arr2.mean(axis = 0) #cálculo da média das colunas

array([-0.39681937,  0.58039514, -0.13974328, -0.06072551])

In [86]:
arr2.sum(axis = 0) #soma dos valores das colunas

array([-0.39681937,  0.58039514, -0.13974328, -0.06072551])

In [87]:
arr

array([ 2.24487054,  1.36573982,  0.30783117,  1.45392678, -0.52869766])

In [101]:
print("A soma de todas observações                        = ", arr.sum())
print("A média das observações                            = ", arr.mean())
print("O desvio-padrão das observações                    = ", arr.std())
print("A variânica das observações                        = ", arr.var())
print("O menor valor das observações                      = ", arr.min())
print("O maior valor das observações                      = ", arr.max())
print("O índice do menor valor das observações            = ", arr.argmin())
print("O índice do maior valor das observações            = ", arr.argmax())
print("A soma cumulativa dos elementos, começando de 0    = ", arr.cumsum())
print("O produto cumulativo dos elementos, começando de 1 = ", arr.cumprod())

A soma de todas observações                        =  4.843670647121197
A média das observações                            =  0.9687341294242394
O desvio-padrão das observações                    =  0.9696024188564005
A variânica das observações                        =  0.9401288506521828
O menor valor das observações                      =  -0.5286976615049542
O maior valor das observações                      =  2.244870538687249
O índice do menor valor das observações            =  4
O índice do maior valor das observações            =  0
A soma cumulativa dos elementos, começando de 0    =  [2.24487054 3.61061036 3.91844153 5.37236831 4.84367065]
O produto cumulativo dos elementos, começando de 1 =  [ 2.24487054  3.06590909  0.94378238  1.37219047 -0.7254739 ]


In [102]:
# Ordenação

In [104]:
arr = np.random.randn(6)
arr

array([-0.40917469,  1.14417159, -0.32216131,  1.29601881,  0.48223418,
        0.92452725])

In [106]:
arr.sort()
arr

array([-0.40917469, -0.32216131,  0.48223418,  0.92452725,  1.14417159,
        1.29601881])

In [107]:
arr = np.random.randn(5, 3)
arr

array([[-0.94518561,  0.02464907,  0.55870215],
       [ 0.39445559, -1.15547641, -0.826354  ],
       [-2.00463286,  0.07986988,  0.56057686],
       [-0.71571757, -1.38520177, -0.07328199],
       [-0.74149865, -1.30312512,  0.67219678]])

In [117]:
arr.sort()
arr

array([[-2.00463286, -0.826354  , -0.07328199],
       [-1.38520177, -0.74149865,  0.39445559],
       [-1.30312512, -0.71571757,  0.55870215],
       [-1.15547641,  0.02464907,  0.56057686],
       [-0.94518561,  0.07986988,  0.67219678]])

In [115]:
arr.sort(1)
arr

array([[-2.00463286, -0.826354  , -0.07328199],
       [-1.38520177, -0.74149865,  0.39445559],
       [-1.30312512, -0.71571757,  0.55870215],
       [-1.15547641,  0.02464907,  0.56057686],
       [-0.94518561,  0.07986988,  0.67219678]])

In [118]:
arr.sort(0)
arr

array([[-2.00463286, -0.826354  , -0.07328199],
       [-1.38520177, -0.74149865,  0.39445559],
       [-1.30312512, -0.71571757,  0.55870215],
       [-1.15547641,  0.02464907,  0.56057686],
       [-0.94518561,  0.07986988,  0.67219678]])

In [ ]:
# Unicidade e Outras Lógicas de Conjunto