# Python 3 para Análise de Dados
### Básico sobre NumPy
    by Adriano Pylro
    Referências:
        1) Pyhton para Análise de Dados (Wes McKinney)

In [1]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
# gera dados aleatórios
data = np.random.randn(2, 3)
data

array([[-0.2934492 ,  0.30468902, -1.04780811],
       [ 2.02686861,  0.47387795,  1.07139317]])

In [6]:
data * 100

array([[ -29.34491994,   30.4689024 , -104.78081098],
       [ 202.68686103,   47.38779469,  107.13931703]])

In [7]:
data + data

array([[-0.5868984 ,  0.60937805, -2.09561622],
       [ 4.05373722,  0.94775589,  2.14278634]])

In [8]:
# um ndarray é um contêiner genérico multidimensional para dados homogêneos

In [9]:
data.shape

(2, 3)

In [10]:
data.dtype

dtype('float64')

In [14]:
data1 = [6, 7 , 8, 9, 10]
data1

[6, 7, 8, 9, 10]

In [15]:
arr1 = np.array(data1)
arr1

array([ 6,  7,  8,  9, 10])

In [17]:
data2 = [[1, 2, 3], [4, 5, 6]]
data2

[[1, 2, 3], [4, 5, 6]]

In [18]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.ndim

2

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2)) 

array([[[6.94363391e-310, 6.94363391e-310],
        [0.00000000e+000, 0.00000000e+000],
        [6.94359463e-310, 4.67997532e-310]],

       [[4.67997532e-310, 4.67997532e-310],
        [4.94065646e-324, 1.08694442e-322],
        [4.67997532e-310, 4.94065646e-324]]])

In [26]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
arr[5]

5

In [28]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11, 12, 13, 14])

In [37]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 69])

In [38]:
arr_slice[2] = 69
arr

array([ 0,  1,  2,  3,  4, 12, 12, 69,  8,  9, 10, 11, 12, 13, 14])

In [39]:
arr_slice[:] = 2019
arr

array([   0,    1,    2,    3,    4, 2019, 2019, 2019,    8,    9,   10,
         11,   12,   13,   14])

In [ ]:
# Indexando com fatias